output_reports = []
for Bioproject in config['in'].keys():
    for CaseName in config['in'][Bioproject].keys():
        output_report = config['out']['outdir']+"/report/"+Bioproject+"/"+CaseName+"_report.txt"
        output_reports.append(output_report)

rule all:
    input:
        output_reports
        # config['out']['outdir']+"/report/PRJNA489159/CMT-100_report.txt",
        # config['out']['outdir']+"/report/PRJNA489159/CMT-102_report.txt",
        # config['out']['outdir']+"/report/PRJNA489159/CMT-103_report.txt",
        # config['out']['outdir']+"/report/PRJNA489159/CMT-105_report.txt",
        # config['out']['outdir']+"/report/PRJNA489159/CMT-106_report.txt",
        # config['out']['outdir']+"/report/PRJNA489159/CMT-107_report.txt",
        # config['out']['outdir']+"/report/PRJNA489159/CMT-109_report.txt",
        # config['out']['outdir']+"/report/PRJNA489159/CMT-111_report.txt",
        # config['out']['outdir']+"/report/PRJNA489159/CMT-112_report.txt",
        # config['out']['outdir']+"/report/PRJNA489159/CMT-114_report.txt"

rule run_pipeline:
    input:
    output:
        report=config['out']['outdir']+"/report/{Bioproject}/{CaseName}_report.txt"
    params:
        Bioproject=lambda wc: wc.Bioproject,
        CaseName=lambda wc: wc.CaseName,
        Normal_Run=lambda wc: config['in'][wc.Bioproject][wc.CaseName][0],
        Tumor_Run=lambda wc: config['in'][wc.Bioproject][wc.CaseName][1],
        outdir=config['out']['outdir'],
        project_dir=config['project_dir'],
        config=config['out']['outdir']+"/config/{Bioproject}_{CaseName}_config.json"
    conda:
        config['envs']['wesenv']
    threads:
        config['resources']['threads']
    resources:
        mem=config['resources']['mem']
    shell:
        '''
        mkdir -p {params.outdir}/data/{params.Bioproject}/{params.CaseName}
        cd {params.outdir}/data/{params.Bioproject}/{params.CaseName}
        python {params.project_dir}/scripts/per_case/make_snakemake_config.py \
            --project_dir {params.project_dir} \
            --out {params.config} \
            --outdir {params.outdir} \
            --Bioproject {params.Bioproject} \
            --Normal_Run {params.Normal_Run} \
            --Tumor_Run {params.Tumor_Run} \
            --CaseName {params.CaseName} \
            --threads {threads} \
            --memory {resources.mem}

        snakemake \
            --cores {threads} \
            --unlock \
            --use-conda \
            --rerun-triggers mtime \
            --configfile {params.config} \
            --snakefile "{params.project_dir}/scripts/per_case/Snakefile"
        '''
